[package]
name = "ame_client"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-core = "0.3.25"
tonic = "0.8.3"
prost = "0.11"
serde = "1.0"

[build-dependencies]
tonic-build = "0.8.4"
prost-build = "0.11.2"
serde = "1.0"
