apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ame.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "ame.labels" (dict "context" . .Values.server.name "name" "cm") | nindent 4 }}
data:
  AME_SERVER_PORT: "3342"
  AME_OBJECT_STORAGE_ENDPOINT: {{ .Values.objectStorage.s3.endpoint }}
  AME_OBJECT_STORAGE_BUCKET: {{ .Values.objectStorage.s3.bucket }}
  AME_MLFLOW_URL: {{ .Values.mlflow.endpoint }}
  AME_MODEL_INGRESS_HOST: {{ .Values.models.deployments.ingress.host }}
  AME_MODEL_DEPLOYMENT_DEFAULT_INGRESS: {{ .Values.models.deployments.defaultIngress }}
  AME_EXECUTOR_IMAGE: {{ .Values.task.image.repository }}:{{ .Values.task.image.tag }}
  AME_OBJECT_STORAGE_SECRET: {{ .Values.objectStorage.s3.secretName }}
  AME_OBJECT_STORAGE_SECRET_KEY: {{ .Values.objectStorage.s3.secretName }}
  AME_OBJECT_STORAGE_SECRET_ID_KEY: {{ .Values.objectStorage.s3.secretName }}

