# Using the `rust-musl-builder` as base image, instead of the official Rust toolchain. 
# See https://github.com/clux/muslrust for why this is desirable.
FROM  clux/muslrust:nightly AS chef
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Notice that we are specifying the --target flag!
RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json
COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl --bin controller

FROM alpine AS runtime
RUN addgroup -S ame && adduser -u 1001 -S -D ame -G ame
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/controller /usr/local/bin/
USER ame
CMD ["/usr/local/bin/controller"]
