# permissions for end users to view reccurringtasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reccurringtask-viewer-role
rules:
- apiGroups:
  - ame.teainspace.com
  resources:
  - reccurringtasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - reccurringtasks/status
  verbs:
  - get
