# permissions for end users to edit reccurringtasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reccurringtask-editor-role
rules:
- apiGroups:
  - ame.teainspace.com
  resources:
  - reccurringtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - reccurringtasks/status
  verbs:
  - get
