apiVersion: v1
kind: Service
metadata:
  name: {{ include "ame.controller.fullname" . }}
  labels:
    {{- include "ame.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }} 
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ame.selectorLabels" . | nindent 4 }}
