[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Jessie Chatham Spencer <--global>"]

[tool.poetry.dependencies]
python = "3.10.9"
numpy = "^1.22"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
