resources:
- ../base/resources

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ame-server
  newName: ghcr.io/teainspace/ame-server/main
  newTag: 5ceb
namespace: ame-system
