apiVersion: v1
kind: ServiceAccount
metadata:
  name: ame-server
  namespace: ame-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ame-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ame-server-role
subjects:
- kind: ServiceAccount
  name: ame-server
  namespace: ame-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ame-server-role
rules:
- apiGroups:
  - ame.teainspace.com
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - tasks/status
  verbs:
  - get
- apiGroups: 
  - ""
  resources: 
  - pods
  - pods/log
  - pods/status
  verbs:
  - get
  - watch
  - list
