apiVersion: apps/v1
kind: Deployment
metadata:
  name: ame-controller
  namespace: ame-system
  labels:
    app: ame-controller
spec:
  selector:
    matchLabels:
      app: ame-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        app: ame-controller
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      imagePullSecrets:
        - name: regcred
      containers:
      - image: ame-controller:latest
        name: controller
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 250Mi
        env:
          - name: EXECUTOR_IMAGE
            valueFrom:
              configMapKeyRef:
                name: ame-controller-configmap
                key: executor_image
          - name: AME_NAMESPACE
            value: ame-system
          - name: AME_MLFLOW_URL
            value: http://mlflow.default.svc.cluster.local:5000
          - name: AME_MODEL_INGRESS_HOST
            value: "20.4.90.180.nip.io"
          - name: RUST_LOG
            value: controller=debug
          - name: AME_MODEL_DEPLOYMENT_INGRESS
            value: |
                apiVersion: networking.k8s.io/v1
                kind: Ingress
                metadata:
                  name: grpc-ingress
                  annotations:
                    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
                    cert-manager.io/cluster-issuer: "letsencrypt-staging"
                spec:
                  ingressClassName: nginx
                  rules:
                  - host: grpc.20.76.43.59.nip.io   
                    http:
                      paths:
                      - path: /
                        pathType: ImplementationSpecific
                        backend:
                          service:
                            name: grpc-service
                            port:
                              number: 50051
                  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
                    - hosts:
                      - 20.76.43.59.nip.io
                      secretName: myingress-cert-grpc # < cert-manager will store the created certificate in this secret.
                      serviceAccountName: ame-controller
                      terminationGracePeriodSeconds: 10
      serviceAccountName: ame-controller
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ame-controller-configmap
data:
  executor_image: ""
