apiVersion: apps/v1
kind: Deployment
metadata:
  name: ame-controller
  namespace: ame-system
  labels:
    app: ame-controller
spec:
  selector:
    matchLabels:
      app: ame-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        app: ame-controller
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      imagePullSecrets:
        - name: regcred
      containers:
      - image: ame-controller:latest
        name: controller
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 250Mi
      serviceAccountName: ame-controller
      terminationGracePeriodSeconds: 10
