apiVersion: v1
kind: ServiceAccount
metadata:
  name: ame-controller
  namespace: ame-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ame-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ame-controller-role
subjects:
- kind: ServiceAccount
  name: ame-controller
  namespace: ame-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ame-controller-role
rules:
- apiGroups:
  - ame.teainspace.com
  resources:
  - reccurringtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - reccurringtasks/finalizers
  verbs:
  - update
- apiGroups:
  - ame.teainspace.com
  resources:
  - reccurringtasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ame.teainspace.com
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - ame.teainspace.com
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - projects/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - projectsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ame.teainspace.com
  resources:
  - projectsources/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
