apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ame.server.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "ame.labels" (dict "context" . .Values.server.name "name" "cm") | nindent 4 }}
data:
  AME_SERVER_PORT: "3342"
  AME_OBJECT_STORAGE_ENDPOINT: {{ .Values.objectStorage.s3.endpoint }}
  AME_OBJECT_STORAGE_BUCKET: {{ .Values.objectStorage.s3.bucket }}
