apiVersion: v1
kind: Service
metadata:
  name: {{ template "ame.server.fullname" . }}
  labels:
    {{- include "ame.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ame.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 4 }}
