[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
either = "1.8.0"
envconfig = "0.10.0"
futures = "0.3.25"
k8s-openapi = { version = "0.16.0", features = ["v1_23", "schemars"] }
kube = { version = "0.76.0", features = ["runtime", "client", "derive"] }
prometheus = "0.13.3"
schemars = "0.8.11"
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"
serde_tuple = "0.5.0"
serde_yaml = "0.9.14"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
insta = {version = "1.21.0", features = ["yaml"] }
serial_test = "0.9.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

