on: push

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ame-ci-cache
          cache-on-failure: "true"
      - name: Prep test environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential openssl libssl-dev libc6-dev clang libclang-dev ca-certificates protobuf-compiler-grpc
          cargo install cargo-binstall
          cargo binstall --force -y just
          just setup_toolchains
          just ci_tools
      - name: Validate commit
        env:
          AME_TEST_GH_TOKEN: ${{ secrets.AME_TEST_GH_TOKEN }}
        run: |
          just check
          just test
      - name: build and push images
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
          just AME_REGISTRY=ghcr.io/teainspace IMG_TAG=/$GITHUB_REF_NAME:$(git rev-parse --short=4 $GITHUB_SHA) publish_images
      - name: push latest images
        if: env.GITHUB_REF_NAME  == 'main'
        run: |
          just AME_REGISTRY=ghcr.io/teainspace IMG_TAG=/$GITHUB_REF_NAME:latest publish_images


