on: push

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.*' # The Go version to download (if necessary) and use.
      - name: Validate commit
        run: make test
