on: push

env:
  IMG: ame-controller:local
  SERVER_IMG: ame-server:local

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.19.4'
      - name: Rust validation
        run: |
          just setup_toolchains
          just tools
          just check
          just setup_cluster
          just install_ame
          just test
      - name: Prep test environment
        run: |
          make tools
          make deploy_local_cluster
      - name: Validate commit
        run: |
          make test
